# In _config.yml
title: Sentiment Analysis
author: Eric Allen

execute:
  execute_notebooks: force

repository:
  url: https://github.com/ericrallen/sentiment-analysis-notebook
  branch: main

html:
  use_repository_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "classic"
  thebe: true
